--https://onedrive.live.com/:x:/g/personal/E11B26EEAACB7947/EYr6VzHqEV5Fg8WNmMLMOAMBf9SH4Koe2urkR5lTreRF4Q?resid=E11B26EEAACB7947!s3157fa8a11ea455e83c58d98c2cc3803&ithint=file%2Cxlsx&e=a4ezg5&migratedtospo=true&redeem=aHR0cHM6Ly8xZHJ2Lm1zL3gvYy9lMTFiMjZlZWFhY2I3OTQ3L0VZcjZWekhxRVY1Rmc4V05tTUxNT0FNQmY5U0g0S29lMnVya1I1bFRyZVJGNFE_ZT1hNGV6ZzU
WITH INDEXED AS
	(SELECT ROW_NUMBER() OVER () AS IND,
			DEPT,
			EMP,
			SALARY
		FROM EMP),
	DEPT_GROUPS AS
	(SELECT *,
			COUNT(DEPT) OVER (
																					ORDER BY IND) AS DEPT_GRP
		FROM INDEXED),
	CLEANED AS
	(SELECT IND,
			FIRST_VALUE(DEPT) OVER(PARTITION BY G.DEPT_GRP) AS DEPT,
			G.EMP,
			G.SALARY
		FROM DEPT_GROUPS AS G)
SELECT CASE
											WHEN ROW_NUMBER() OVER(PARTITION BY DEPT) > 1 THEN NULL
											ELSE DEPT
							END AS DEPT,
	EMP,
	DEP_MAX AS MAX_SALARY
FROM CLEANED AS C1
JOIN LATERAL
	(SELECT MAX(SALARY) AS DEP_MAX
		FROM CLEANED AS C2
		WHERE C2.DEPT = C1.DEPT ) AS TOPS ON TRUE
WHERE SALARY = DEP_MAX
ORDER BY IND